steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "https://github.com/humbertopaiva/gcp-rdstation-backend.git"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "gcr.io/headless-site/wordpress"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/headless-site/wordpress"

  # PVC
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-pvc.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # JOB
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-content-sync.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # DEPLOYMENT
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # SERVICE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-service.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # # Check rollout status
  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     - "rollout"
  #     - "status"
  #     - "deployment/wordpress"
  #   env:
  #     - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
  #     - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

images:
  - "gcr.io/headless-site/wordpress:v1.0.1"
