steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "https://github.com/humbertopaiva/gcp-rdstation-backend.git"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "gcr.io/headless-site/wordpress:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/headless-site/wordpress:latest"

  # PVC
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-pvc.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # Delete existing JOB (if any)
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "delete"
      - "job"
      - "wordpress-content-sync"
      - "--ignore-not-found" # Ignore error if the Job doesn't exist
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # JOB
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-content-sync.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

    # JOB
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-service-lb.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # Antes de aplicar o deployment
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "kubernetes/wordpress-deployment.yaml",
        "kubernetes/wordpress-deployment-tmp.yaml",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed "s|CURRENT_TIMESTAMP|$(date +%s)|g" kubernetes/wordpress-deployment-tmp.yaml > kubernetes/wordpress-deployment-timestamp.yaml

  # DEPLOYMENT
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # SERVICE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-service.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

    # SERVICE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/wordpress-ingress.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

images:
  - "gcr.io/headless-site/wordpress:latest"
