steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "https://github.com/humbertopaiva/gcp-rdstation-backend.git"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "gcr.io/headless-site/wordpress:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/headless-site/wordpress:latest"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "kubernetes/"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     - "set"
  #     - "image"
  #     - "deployment/wordpress"
  #     - "wordpress=gcr.io/headless-site/wordpress:latest"
  #   env:
  #     - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
  #     - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "rollout"
      - "status"
      - "deployment/wordpress"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-rdstation-teste"

images:
  # Imagem Docker gerada no passo anterior
  - "gcr.io/headless-site/wordpress:latest"
