version: "3.8"

services:
  wordpress:
    image: wordpress:6.1
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "sqlpassword"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - rdstation-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "sqlpassword"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - rdstation-network

volumes:
  wordpress:
  db:

networks:
  rdstation-network:
    external: true
