version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "sqlpassword"
    volumes:
      - ./wordpress:/var/www/html
      - ./credentials.json:/secrets/cloudsql/key.json
    depends_on:
      - db
      - cloudsql-proxy

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "sqlpassword"
    volumes:
      - ./db:/var/lib/mysql

  # cloudsql-proxy:
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
  #   command: /cloud_sql_proxy -instances=headless-site:us-central1:sql-rdstation-teste=tcp:3306 -credential_file=/secrets/cloudsql/key.json
  #   volumes:
  #     - ./credentials.json:/secrets/cloudsql/key.json

volumes:
  wordpress:
  db:
