version: "3.8"

services:
  wordpress:
    image: wordpress:6.1
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "sqlpassword"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - cloudsql-proxy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "sqlpassword"
    volumes:
      - ./db:/var/lib/mysql

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
    command: /cloud_sql_proxy -instances=headless-site:us-central1:sql-instance=tcp:3306 -credential_file=/secrets/cloudsql/credentials.json
    volumes:
      - ./secrets/cloudsql-proxy/:/secrets/cloudsql/

volumes:
  wordpress:
  db:
